name: win-ca-smoke-self-test

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  smoke:
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    uses: ./.github/workflows/win-ca-smoke.yml
    with:
      node-version: ${{ matrix.node }}
      pre-step-name: Verify HTTPS fails before trust
      post-step-name: Verify HTTPS succeeds after trust
      pre-test-command: pwsh -File scripts/Test-WinCA.ps1
      post-test-command: pwsh -File scripts/Test-WinCA.ps1
      pre-step-extra-env: '{"WIN_CA_EXPECT_SUCCESS":"0","WIN_CA_HOST":"https://127.0.0.1:4443/"}'
      post-step-extra-env: '{"WIN_CA_EXPECT_SUCCESS":"1","WIN_CA_HOST":"https://127.0.0.1:4443/"}'
